# Site settings
title: "Base 2 Earth"
description: "Software development, geospatial topics & free pegasus rides"
baseurl: ""
url: "http://aaronjcaldwell.github.io/"
tagline: "Software development, geospatial topics & free pegasus rides"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: false
    input: GFM 
    syntax_highlighter: rouge
gems: [jekyll-paginate, rouge]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
