# Site settings
title: "Base Two World"
description: "Software development, geospatial topics & free pegasus rides"
baseurl: ""
url: "http://aaronjcaldwell.github.io/"
tagline: "Software development, geospatial topics & free pegasus rides"

# Build settings
markdown: kramdown
kramdown:
    auto_ids: false
gems: [jekyll-paginate]
paginate: 4
paginate_path: '/blog/page:num/'
permalink: /blog/:title
